image: node:latest

pages:
  stage: deploy
  tags:
    - shared-fi
  script:
    - mkdir public
    - cd app
    - npm install
    - npm run build
    - cp -r ./dist/* ../public
  artifacts:
    paths:
    - public
  only:
  - main
